
DROP DATABASE if exists wow_heroes;
CREATE DATABASE wow_heroes;
USE wow_heroes;

CREATE TABLE ADMINISTRADOR(
CEDULA VARCHAR(10) NOT NULL,
CONTRASENA VARCHAR(100) NOT NULL,
PRIMARY KEY (CEDULA)
)ENGINE=InnoDB;

INSERT INTO ADMINISTRADOR (CEDULA, CONTRASENA) VALUES ('000', '123');

CREATE TABLE HERO(
NOMBRE VARCHAR(50) NOT NULL,
RAZA VARCHAR(50) NOT NULL,
SEXO VARCHAR(1) NOT NULL,
FACCION VARCHAR(10) NOT NULL,
PRIMARY KEY (NOMBRE)
)ENGINE=InnoDB;

INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('ARTHAS', 'HUMAN', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('ILLIDAN', 'NIGHT-ELF', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('SYLVANAS', 'UNDEAD', 'F', 'HORDE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('THRALL', 'ORC', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('JAINA', 'HUMAN', 'F', 'ALLIANCE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ("KAEL'THAS", 'BLOOD-ELF', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('TYRANDE', 'NIGTH-ELF', 'F', 'ALLIANCE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('CAIRNE', 'TAUREN', 'M', 'HORDE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('REXXAR', 'ORC', 'M', 'HORDE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('CENARIUS', 'UNKNOWN', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ("KEL'THUZAD", 'UNKNOWN', 'M', 'NONE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('GROMASH HELLSCREAM', 'ORC', 'M', 'HORDE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('MALFURION', 'NIGHT-ELF', 'M', 'ALLIANCE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('MURADIN', 'DWARF', 'M', 'ALLIANCE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('VARIAN', 'HUMAN', 'M', 'ALLIANCE');
INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION) VALUES ('MEDIVH', 'HUMAN', 'M', 'NONE');

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_heroes` ()
BEGIN
	SELECT *
	FROM HERO;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_hero` (
	IN nom VARCHAR(50), IN raz VARCHAR(50), IN sex VARCHAR(1), IN fac VARCHAR(10))
BEGIN
	INSERT INTO HERO (NOMBRE, RAZA, SEXO, FACCION)
    VALUES (nom, raz, sex, fac);
END$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `delete_hero` (
	IN nom VARCHAR(50))
BEGIN
	DELETE
    FROM HERO
    WHERE NOMBRE=nom;
END$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_hero` (IN o_nom VARCHAR(50),
	IN nom VARCHAR(50), IN raz VARCHAR(50), IN sex VARCHAR(1), IN fac VARCHAR(10))
BEGIN
	UPDATE HERO
	SET NOMBRE=nom, RAZA=raz, SEXO=sex, FACCION=fac
	WHERE NOMBRE=o_nom;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `seek_hero`(IN nom varchar(50))
BEGIN
	SELECT * 
    FROM HERO 
    WHERE NOMBRE LIKE nom;
END$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `count_raz`()
BEGIN
	SELECT RAZA, count(*) AS counter
	FROM HERO
	GROUP BY RAZA
	ORDER BY counter DESC;
END$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `count_sex`()
BEGIN
	SELECT SEXO, count(*) AS counter
	FROM HERO
	GROUP BY SEXO
	ORDER BY counter DESC;
END$$
DELIMITER ;


DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `count_fac`()
BEGIN
	SELECT FACCION, count(*) AS counter
	FROM HERO
	GROUP BY FACCION
	ORDER BY counter DESC;
END$$
DELIMITER ;






